Ad 185421 v2
SkillsFundingAgency/dss-interaction pull request #37
Opened 2024-08-09 11:51 UTC by amjones99

2024-08-09 13:29 UTC, bmatthews-DFE commented on NCS.DSS.Interaction/APIDefinition/APIDefinition.cs
Don't forget to increment the API version #

2024-08-09 13:29 UTC, bmatthews-DFE commented on NCS.DSS.Interaction/NCS.DSS.Interaction.csproj
> +    <ImplicitUsings>enabled</ImplicitUsings>
Replace `<ImplicitUsings>enabled</ImplicitUsings>` with `<ImplicitUsings>enable</ImplicitUsings>`

2024-08-09 13:33 UTC, bmatthews-DFE reviewed
This build appears to have obselete warnings;
![image](https://github.com/user-attachments/assets/848a5163-ea92-4dc1-bc02-a2621860d42a)

2024-08-12 15:06 UTC, PradeepVoorukonda requested changes
few suggestions / comments

2024-08-12 15:06 UTC, PradeepVoorukonda commented on NCS.DSS.Interaction/PostInteractionHttpTrigger/Function/PostInteractionHttpTrigger.cs
_httpResponseMessageHelper and jsonHelper not used any more. These references can be removed

2024-08-12 15:06 UTC, PradeepVoorukonda commented on NCS.DSS.Interaction/PatchInteractionHttpTrigger/Function/PatchInteractionHttpTrigger.cs
_httpResponseMessageHelper and jsonHelper not used any more. These references can be removed

2024-08-12 15:06 UTC, PradeepVoorukonda commented on NCS.DSS.Interaction/GetInteractionHttpTrigger/Function/GetInteractionHttpTrigger.cs
_httpResponseMessageHelper and jsonHelper not used any more. These references can be removed

2024-08-12 15:14 UTC, amjones99 commented on NCS.DSS.Interaction/APIDefinition/APIDefinition.cs
yes that is correct. It was incorrectly set to 2 before before

2024-08-12 15:29 UTC, PradeepVoorukonda approved these changes

2024-08-13 09:19 UTC, merged